### ISSUE TITLE
Can't get range and depth plots to line up

### ISSUE THREAD

**Issue by zoekitchel** [pinskylab/ARMS_ClimateShift#1]
@mstuart1 , if you have a chance sometime before Friday, would you mind playing around with line 207 on? first is code for plot for range, and then is code for plot for depth. I'd like the Y axis labels and the y=0 lines to line up, ideally, but can't figure it out with either ggpubr::ggarrange() or cowplot::plot_grid. Thanks!

**Comment by mstuart1** [comment]
I can't get your code to run at line 55.  

However, try plugging your plots (2.5 & 3.5) into this function, as in, source the function to make it active, and then call `multiplot(plot2.5, plot3.5, cols=2)`. 

It's possible that you can loose some lines in the code that makes plot2.5 and plot3.5 if those lines were just to position them next to each other.

This will plot the bottom 2 plots as B and C next to each other but doesn't deal with A, although in the directions below it looks like you can set that up, I just didn't play with it because I couldn't get the code to run.  The formatting for this code is whacky because GitHub formatting is not cooperating. :/
*This is copied from [SJOLeary - ggplot script](https://github.com/sjoleary/SNPFILT/blob/master/scr/ggplot.R#L36-L81)*
Multiple plot function (http://www.cookbook-r.com/Graphs/Multiple_graphs_on_one_page_(ggplot2)/)
ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
 - cols:   Number of columns in layout
 - layout: A matrix specifying the layout. If present, 'cols' is ignored.

 If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
 then plot 1 will go in the upper left, 2 will go in the upper right, and
 3 will go all the way across the bottom.

`multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)`
`  # Make a list from the ... arguments and plotlist`
 ` plots <- c(list(...), plotlist)
  numPlots = length(plots)`
  `# If layout is NULL, then use 'cols' to determine layout`
 ` if (is.null(layout)) {`
   ` # Make the panel`
  `  # ncol: Number of columns of plots`
  `  # nrow: Number of rows needed, calculated from # of cols`
  `  layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                     ncol = cols, nrow = ceiling(numPlots/cols))
  }
  if (numPlots==1) {
    print(plots[[1]])  
  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}`

**Comment by mstuart1** [comment]
After messing with the formatting of this code so much, I see that you could pass the map too, so it would be..

multiplot(map1, plot2.5, plot3.5, layout = matrix(c(1,1,2,3), nrow=2, byrow=TRUE)

**Comment by zoekitchel** [comment]
Thanks for your help! I figured it out by tweaking some margins. Not graceful...but functional
